= Objekte
:doctype: article
:icons: font
:imagesdir: ../images/
:web-xmera: https://xmera.de


== Basisobjekte

Die Objekte der obersten Hierarchieebene heißen Basisobjekte. Sie übernehmen die Funktion von Arbeitsbereichen, die individuell ausgebaut werden können. 

=== A Management
Im Arbeitsbereich "Management" werden die Datenschutz- und der Informationssicherheitssicherheitsmanagementprozesse geplant, koordiniert, durchgeführt und überwacht. 

In dieser Objektebene können Richtlinien und andere Dokumente zentral und managementsystemübergreifend verwaltet und gelenkt werden. 

==== DSGVO
Eine gesetzeskonforme Umsetzung des Datenschutzes erfordert eine gute Organisation und Koordination. In diesem Arbeitsbereich kann der Datenschutzbeauftragte seine Aufgaben planen.

==== ISMS

Die Einführung und der Betrieb des ISMS wird in diesem Arbeitsbereich geplannt. 

=== B Prozesse & Informationen

Prozesse und Informationen bilden die primären Werte einer Organisation. Ihr Schutzbedarf ist Ausgangspunkt für alle weiteren zu treffenden Sicherheitsmaßnahmen.

Geschäftsprozesse erzeugen, verarbeiten oder speichern Informationen. Die Schutzziele Vertraulichkeit und Integrität werden typischerweise auf Informationen abgebildet. Die Verfügbarkeit dagegen, ist ein typisches Schutzziel für einen Prozess.

In diesem Bereich wird der Schutzbedarf von Geschäftsprozessen und Informationsobjekten der Organisation bewertet.

=== C Personal

Mitarbeiter müssen in den Informationssicherheitsprozess integriert werden und Sicherheit aktiv mitgestalten. Dazu bedarf es organistorischer Regeln, die sich über den gesamten Beschäftiungszyklus erstrecken.

Richtlinien, Regelungen und Maßnahmen, die direkten Personalbezug haben, können in diesem Bereich geplant werden.


=== D IT-Betrieb

Der gesamte IT-Verbund hat unterstützende Funktion. Hierzu gehören beispielsweise Anwendungen, Endgeräte, Server und Netzwerk. Der Schutzbedarf der Prozesse und Informationen vererbt sich auf diese sekundären Werte. Schutzbedarf, Risikomanagement und die Maßnahmensteuerung sind wesentliche Aufgaben, die im Bereich 'IT-Betrieb' umgesetzt werden.


=== E Infrastruktur

Zur Infrastruktur gehören Versorgungs-, Arbeitsbereiche und das mobile Arbeiten. Sie werden in diesem Bereich abgebildet.

=== F Changeprojekte

Für komplexe Maßnahmen zur Steigerung der Informationssicherheit können im Bereich "Changeprojekte" Unterobjekte erstellt werden.

=== G Audit

Die Auditplanung findet in diesem Bereich statt.

=== H Meldungen

Störungen und Vorfälle sind Meldungen, die im Bereich "Meldungen" eingehen.

=== I Handbücher

Unternehmensweite Handbücher, auf die alle Mitarbeiter Zugriff haben.