= Rollen und Rechte
:doctype: article
:icons: font
:imagesdir: ../images/
:web-xmera: https://xmera.de

Die Rechte zur Bedienung von xmera Omnia sowie die Workflows für die Statusführung von Aufgaben werden über Rollen gesteuert. Die Zuordnung der Rollen zu den Benutzern erfolgt (bis auf die Rolle Administrator) in den Objekten. Somit können einem Benutzer in verschiedenen Objekten unterschiedliche Rollen zugewiesen werden.

== Basisrollen
Die Basisrollen sind die Rollen im System, mit denen funktional die Abläufe eines ISMS abgebildet werden können. Sie können als Grundlage für die Erstellung weiterer Rollen dienen, die von diesen Basisrollen die Rechte und Workflows übernehmen können.

=== Administrator
Die Rolle des Administrators wird nicht als veränderbare Rolle im Bereich "Rollen und Rechte" verwaltet, sondern einem oder mehreren Benutzen im Bereich der Benutzterverwaltung zugewiesen. Mit der Festlegung erhält der Benutzer, unabhägig von den sonstigen Rollenzuordnungen, *alle Rechte* im System. Nur Beutzer mit der Admin-Zuordnung haben Zugriff auf den Administrationsbereich von xmera Omnia.

=== Objektverantwortlich
Der Objektverantwortliche konfiguriert ein Objekt. Er ist für die Beschreibung des Objektes, die Auswahl und Ausgestaltung der Module in dem Objekt sowie die Zuordung der Benutzer mit ihren Rollen in dem Objekt verantwortlich.

=== Überwachungsverantwortlich
Der  Überwachungsverantwortliche ist bei Aufgabentypen, bei denen ein 4-Augenprizip gefordert ist, für die Überprüfung der operativ erledigten Aufgaben verantwortlich. Nur der Überwachungsverantwortliche kann bei diesen Aufgabentypen die Status auswählen, die eine Aufgabe schließen.

=== Risikoverantwortlich
Der Risikoverantwortliche verantwortet im Unternehmen die Risiken. Er ist in die Workflows eingebunden, in denen ein Risiko bewertet werden muss.

=== Aufgabenverantwortlich
Der Aufgabenverantwortliche ist für die Pflege des Objektes bis zur operativen Erledigung der Aufgabe verantwortlich.

=== Nichtmitlglied
Die Rolle Nicht-Mitglied ist eine globale Rollenbeschreibung für öffentliche Objekte. Die Rolle definiert die Rechte eines angemeldeten Benutzers, die er ohne zugewiesen Rolle in dem öffentlichen Objekt hat. 

=== Anonym
Die Rolle Annonym ist nur relevant, wenn xmera Omnia so konfiguriert wurde, dass eine Authentifizierung nicht notwendig ist. Die Rolle Anonym ist in diesem Fall eine globale Rollenbeschreibung, die die Rechte eines Nutzers definiert, der nicht angemeldet ist. Ein nicht angeldeter Nutzer hat mit den Rechten der Rolle Anonym Zugriff auf alle öffentlichen Objekte.


== Definition von Rollen

Die Definition von Rollen beinhaltet Einstellung zur Aufgabendelegation, Sichtbarkeit von Aufgaben, Zeiten und Benutzern sowie Berechtigungen zur Nutzung der einzelnen Objektmodule.

=== Aufgabendelegation

Es besteht die Möglichkeit eine Rolle aus der Aufgabendelegation auszuschließen. Dieser Rolle können dann keine Aufgaben zugeordnet werden.

=== Sichtbarkeit

Eine gut durchdachte Struktur in der Objekthierarchie legt die Basis zur Bildung von in sich abgeschlossenen Arbeitsbereichen. Neben den modulbezogenen Berechtigungen lässt sich die Sichtbarkeit von Aufgaben, Zeiten und Benutzern weiter einschränken.

==== Aufgaben

Einer Rolle kann eine von drei Optionen zugeordnet werden. Sie regelt die generelle Sichtbarkeit der Aufgaben. Zusätzlich kann die Sichtbarkeit auf bestimmte Aufgabentypen beschränkt werden. 

Ein Benutzer würde demnach beispielsweise alle Aufgaben vom Aufgabentyp Störung sehen oder aber lediglich die Störungen, die er erstellt oder ihm zugewiesen wurden.

===== Option: Alle Aufgaben

Mit dieser Rolle sieht ein Benutzer alle Aufgaben von Objekten, in denen er diese Rolle hat.

===== Option: Alle öffentlichen Aufgaben

Bei der Auswahl dieser Option kann der Rolleninhaber keine privaten Aufgaben sehen.

===== Option: Aufgaben, die der Benutzer erstellt hat oder ihm zugewiesen sind

Die dritte Option schränkt die Sichtbarkeit der Aufgaben auf genau die diejenigen ein, an denen er beteiligt ist. 


==== Zeiten

==== Benutzer

=== Berechtigungen

