= Aufgabentyp
:doctype: article
:icons: font
:imagesdir: ../images/
:web-xmera: https://xmera.de

Die Aufgabentypen repräsentieren die verschiedenen Tätigkeiten, die im Rahmen des Betriebs durchzuführen und zu dokumentieren sind . Jedem Aufgabentyp können zum einen eigene Felder zugeordnet werden und je Aufgabentyp können in zusammenspiel mit den Rollen spezifische Workflows und Feldberechtigungen definiert werden.

== Basis-Aufgabentypen
Die Basis-Aufgabentypen sind vordefinierte Aufgabentypen im System, mit denen funktional die Abläufe eines ISMS abgebildet werden können. Sie können als Grundlage für die Erstellung weiterer Aufgabentypen dienen, die von diesen Basis-Aufgabentypen eigene Felder, Workflows und Feldberechtigungen übernehmen können.

=== Aufgabe
Bei dem Aufgabentyp "Aufgabe" handelt sich um den Standardtyp der eine operative Aufgabe, z. B.

- Wartung,
- Instandhaltung,
- Update- oder Upgrade,
- Inbetriebnahme oder
- Demontage / Rückbau.

Dem Aufgabentyp sind keine eigenen Felder zugeordet. 

=== Störung
Bei dem Aufgabetyp "Störung" handelt es sich um eine Aufgabe zur Behebung einer Störung. Dieser Aufgabentyp dient zum Management des Entstöprozesses und nicht dem Incident-Management. Bei Störungen, die als sicherheitsrelvant eingestuft werden, ist eine gesonderte Aufgabe vom Typ "Vorfall" anzulegen. (Kopie vom Typ "Vorfall")

=== Vorfall
Mit dem Aufgabentyp Vorfall wird das Vorfall-Management (Incident-Management) durchgeführt. Das Vorfallmanagement beinhaltet in der Standarversion eigene Felder, die die https://de.wikipedia.org/wiki/5-Why-Methode[5 W-Metode] abbilden.

Die Dokumentation der Maßnahmen, die sich aus der Analyse ergeben, werden als Unteraufgaben abgebildet werden.

=== Risikobewertung
Mit dem Aufgabentyp "Risikobewertung" wird die Einschätzung des Risikos aus einer Bedrohung dokumentiert. Als Quellen
für Bedrohungsszenarien kommen folgende in Betracht

- Normen (BSI-Grundschutz, ISO 27005, NIST 800-30)
- aus sonstigen unternehmenspezifischen Vorgaben (manuelle Erfassung)

Zusatzmaßnahmen zur Risikominimierung werden als Verknüpfung oder Unteraufgabe zugeordnet und dokumentiert.

=== Sicherheitsanforderung
Eine Sicherheitsanforderung ensteht aus den Vorgaben der Normen (BSI-Grundschutz, ISO 27000, ISIS12, ...).

=== Maßnahme
Eine Maßnahme beschreibt eine Aufgabe zur Erreichung eines sicheren Betriebs. Als Quellen dienen Maßnahmen

- aus dem Vorfallmanagement (Maßnahme aus der Vorfall-Analyse)
- aus dem Risikomanagement (Maßnahme aus der Risikobewertung)
- aus sonstigen unternehmensspezifischen Vorgaben (manuelle Erfassung)

Einer Maßnahme können weitere operative Unteraufgaben zugeordnet werden, die für die Umsetzung der Maßnahme notwendig sind.

Dem Aufgabentyp "Maßnahme" sind eigene Felder zur Bewertung der Wirksamkeit zugeordnet.

=== Verarbeitungstätigkeit
Zu jedem Prozess können über den Aufgabentyp Verarbeitungstätigkeit die Dokumentation der Verarbeitungsvorgänge von personenbezogenen Daten gemäß der Datenschutz-Grundverordnung (DSGVO) und in der Gesamtheit der Verabeitungstätigkeiten das Verzeichnis von Verarbeitungstätigkeiten erstellt werden. Hierzu sind bereits Fragen und Kathaloge vorbereitet über die eigenen Felder vorbereitet. Diese dienen der Unterstützung der Administaration und zeigen einen Überblick der Themen. Die Richtigkeit und Vollständigkeit der Dokumentation der Verarbeitungstätigkeit gem DSGVO liegt in der Verantwortung des Nutzers.

=== Prüfung
Der Aufgabentyp Prüfung dient der Planung und Abbildung von Audits und Revisionen des ISMS.
Es sind keine spezifischen eigenen Felder zugeordnet.
