= Aufgabenstatus
:doctype: article
:icons: font
:imagesdir: ../images/
:web-xmera: https://xmera.de

== Basis-Aufgabenstatus
Die Basis-Aufgabenstatus sind vordefinierte Aufgabenstus im System, mit denen funktional der Aufgabenfortschritt abgebildet werden kann. Dabei ist neben der Aufgabenbearbeitung auch die Überprüfung / Abnahme der Aufgabe mit bestandteil des Prozesses.
Im Zusammenspiel mit den Aufgabentypen und den Rollen werden die Aufgabenstatus zur Steuerung des Workflows genutzt.

=== Neu
Eine neue Aufgabe wird angelegt.

=== Bewertung
Ein Vorfall oder ein Risiko werden bewertet bzw. analysiert.

=== In Bearbeitung
Die Aufgabe wird operativ bearbeitet

=== Bearbeitet
Die Arbeiten and der Aufgabe wurde von dem Aufgabenverantwortlichen abgeschlossen.

=== Feedback
Zur Lösung der Aufgabe gibt es Anmerkungen durch den Überwachungs- bzw. Objektverantworlichen 

=== Geprüft
Die Ausführung der Aufgabe wurde von einem Überwachungsverantwortlichen überprüft und freigegeben.

=== Erledigt (Beendet)
Die erledigte Aufgabe wurde endgültig abgeschlossen und muss nicht weiter bearbeitet werden.

=== Storniert
Eine stornierte Aufgabe besteht in der beschriebenen Form nicht mehr und muss damit nicht weiter verfolgt werden.
