= Objekte
:doctype: article
:icons: font
:imagesdir: ../images/
:web-xmera: https://xmera.de

Objekte sind die kleinste Systemeinheit. Ein Objekt ist ein in sich abgeschlossener Bereich, in dem verschiedene Module aktiviert werden können. Beipiele für Module sind: Aufgaben, Wiki, Dokumente, Meldungen, u.a.

Für jedes Objekt können Unterobjekte erstellt werden. So lässt sich mit Objekten eine hierarchische Strukur aufbauen.

== Basisobjekte

Die Objekte der obersten Hierarchieebene heißen Basisobjekte. Sie übernehmen die Funktion von Arbeitsbereichen, die individuell ausgebaut werden können. 

=== A Management
Im Arbeitsbereich "Management" werden die Datenschutz- und der Informationssicherheitssicherheitsmanagementprozesse geplant, koordiniert, durchgeführt und überwacht. 

In dieser Objektebene können Richtlinien und andere Dokumente zentral und managementsystemübergreifend verwaltet und gelenkt werden. 

==== DSGVO
Eine gesetzeskonforme Umsetzung des Datenschutzes erfordert eine gute Organisation und Koordination. In diesem Arbeitsbereich kann der Datenschutzbeauftragte seine Aufgaben planen.

==== ISMS

Die Einführung und der Betrieb des ISMS wird in diesem Arbeitsbereich geplannt. 

=== B Organisation und Personal

Im Bereich "Organisation und Personal" werden die kritischen Prozesse bearbeitet und informationssicherheitsrelevante Themen rund um das Personal dokumentiert.

=== C Anwendungen

In diesem Bereich wird für jede kritische Anwendung ein Objekt generiert.

=== D IT-Systeme und Netze

Die notwendigen Systeme, die von den kritischen Anwendungen benötigt werden, sind diesem Bereich untergeordnet.

=== E Infrastruktur

Zur Infrastruktur gehören Versorgungs- und Arbeitsbereiche. Sie werden in diesem Bereich abgebildet.

=== F Changeprojekte

Für komplexe Maßnahmen zur Steigerung der Informationssicherheit können im Bereich "Changeprojekte" Unterobjekte erstellt werden.

=== G Audit

Die Auditplanung findet in diesem Bereich statt.

=== H Meldungen

Störungen und Vorfälle sind Meldungen, die im Bereich "Meldungen" eingehen.

=== I Handbücher

Unternehmensweite Handbücher, auf die alle Mitarbeiter Zugriff haben.