= Rollen und Rechte
:doctype: article
:icons: font
:imagesdir: ../images/
:web-xmera: https://xmera.de

Die Rechte zur Bedienung von xmera Omnia werden über Rollen gesteuert. 

Die Zuordnung der Rollen zu den Benutzern erfolgt (bis auf die Rolle Administrator) in den Objekten. 

Somit können einem Benutzer in verschiedenen Objekten unterschiedliche Rollen zugewiesen werden. Erhält ein Benutzer in einem Objekt mehrere Rollen, wirken diese kumulativ.

Die Definition von Rollen wird hauptsächlich im Administrationsbereich unter _Rollen und Rechte_ vorgenommen. Weitere Einstellungsmöglichkeiten zur Sichtbarkeit sind in den Bereichen _Workflows_ und _Eigene Felder_ möglich. 

== Definition von Rollen

Die Definition von Rollen beinhaltet Einstellungen zur Aufgabendelegation, Sichtbarkeit von Aufgaben, Zeiten und Benutzern sowie Berechtigungen zur Nutzung der einzelnen Objektmodule.

Die grundsätzliche Sichtbarkeit von Aufgaben, Zeiten und Benutzern bildet die erste Berechtigungsebene. 

Eine zweite Berechtigungsebene bilden die Module, aus denen eine Rolle wahlweise ausgeschlossen werden kann.

Die dritte Ebene umfassst die Berechtigungen innerhalb eines Moduls.

=== Aufgabendelegation

Es besteht die Möglichkeit eine Rolle aus der Aufgabendelegation auszuschließen. Dieser Rolle können dann keine Aufgaben zugeordnet werden.

=== Sichtbarkeit von Aufgaben

Jede der nachfolgenden Optionen bestimmt die generelle Sichtbarkeit von Aufgaben für eine Rolle in einem Objekt.

Alle Aufgaben::

Mit dieser Rolle sieht ein Benutzer alle öffentlichen und alle privaten Aufgaben in einem Objekt.

Alle öffentlichen Aufgaben::

Bei der Auswahl dieser Option kann der Rolleninhaber keine privaten Aufgaben sehen.

Aufgaben, die der Benutzer erstellt hat oder ihm zugewiesen sind::

Die dritte Option schränkt die Sichtbarkeit der Aufgaben auf genau die diejenigen ein, an denen er beteiligt ist. 

[NOTE]
Die Sichtbarkeit von Aufgaben lässt sich über den _Aufgabentyp_ weiter einschränken. 

=== Sichtbarkeit von Zeiten

=== Sichtbarkeit von Benutzern

=== Berechtigungen für Module

==== Objekt

==== Foren


==== Kalender

==== DMS


==== Dokumente

==== Dateien

==== Verlauf

==== Aufgaben-Synchronisation

==== Aufgaben

Aufgaben anzeigen:: 
  Der Benutzer darf Aufgaben lesen.

Aufgaben hinzufügen::
  Der Benutzer darf Aufgaben erstellen.

Aufgaben bearbeiten::
  Der Benutzer darf in allen Aufgaben Felder wie bspw. Thema, Priorität, Status usw. bearbeiten.

Eigene Aufgaben bearbeiten:: 
  Der Benutzer darf lediglich Aufgaben, die er selbst erstellt hat, bearbeiten. Aufgaben, die ihm zugeordnet wurden, kann er mit diesem Recht nicht bearbeiten.

Aufgaben kopieren:: 
  Der Benutzer darf Aufgaben innerhalb des Objektes und je nach Systemkonfiguration auch zu anderen Objekten durch kopieren hinzufügen.

Aufgaben-Beziehungen verwalten::
  Der Benutzer darf Beziehungen zu anderen Aufgaben herstellen und wieder entfernen.

Untergeordnete Aufgaben verwalten:: 
  Der Benutzer darf Aufgaben anderen Aufgaben unterordnen und die Unterordnung wieder aufheben.

Aufgaben als privat oder öffentlich markieren:: 
  Der Benutzer darf eine beliebige Aufgabe als privat markieren und wieder aufheben. Eine private Aufgabe ist nur für die Benutzer sichtbar, die alle Aufgaben sehen dürfen, siehe <<_sichtbarkeit_von_aufgaben>>. 

Eigene Aufgaben privat oder öffentlich markieren:: 
  Der Benutzer darf lediglich Aufgaben, die er selbst erstellt hat, als privat markieren und wieder aufheben.

Kommentare hinzufügen:: 
  Der Benutzer darf einen Kommentar zu einer Aufgabe hinzufügen.

Kommentare bearbeiten:: 
  Der Benutzer darf Kommentare an Aufgaben bearbeiten.

Eigene Kommentare bearbeiten:: 
  Der Benutzer darf Kommentare, die er selbst erstellt hat, bearbeiten.

Private Kommentare sehen:: 
  Der Benutzer darf private Kommentare von anderen Benutzern sehen.

Kommentar als privat markieren:: 
  Der Benutzer seine Kommentare als privat markieren.

Aufgabe löschen:: 
  Der Benutzer darf eine Aufgabe löschen.

Liste der Beobachter ansehen:: 
  Der Benutzer darf sehen, welche Mitglieder eine Aufgabe beobachten.

Beobachter hinzufügen::
  Der Benutzer darf Mitglieder als Beobachter für eine Aufgabe definieren.

Beobachter löschen:: 
  Der Benutzer darf Beobachter einer Aufgabe wieder entfernen.

Aufgaben importieren:: 
  Der Benutzer darf Aufgaben mittels CSV-Datei importieren.

Aufgaben-Kategorien verwalten:: 
  Der Benutzer darf Aufgaben-Kategorien erstellen an Mitglieder zuordnen, bearbeiten und löschen.

==== Mitteilung

==== Archiv

==== Zeiterfassung

==== Wiki


=======
Ein Benutzer würde demnach beispielsweise alle Aufgaben vom Aufgabentyp Störung sehen oder aber lediglich die Störungen, die er erstellt oder ihm zugewiesen wurden.
=======